#!/usr/bin/env python3
"""Resolve, verify and download the model shortlist (cache/models.yaml) into cache/models/.

Network is allowed here (CLAUDE.md §3). Writes cache/MANIFEST.md with repo id, revision
(HF commit sha), file, sha256 and size for every artifact, so nothing is "cached" without
a hash to show for it.

    uv run python tools/download_models.py --verify            # check repo ids, list files
    uv run python tools/download_models.py --name qwen3.5-0.8b-q4
    uv run python tools/download_models.py --all               # every verified entry
    uv run python tools/download_models.py --manifest          # rebuild MANIFEST.md from disk
"""

from __future__ import annotations

import argparse
import fnmatch
import hashlib
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
MODELS_YAML = REPO_ROOT / "cache" / "models.yaml"
CACHE_DIR = REPO_ROOT / "cache" / "models"
MANIFEST = REPO_ROOT / "cache" / "MANIFEST.md"
LEDGER = REPO_ROOT / "cache" / "manifest.yaml"  # machine-readable twin of MANIFEST.md


@dataclass
class Entry:
    name: str
    tier: str
    role: str
    repo: str
    file: str
    revision: str
    license: str
    lang_pl: bool
    verified: bool
    notes: str = ""


def load_entries(path: Path = MODELS_YAML) -> list[Entry]:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    return [Entry(**{**m, "tier": str(m["tier"])}) for m in data["models"]]


def sha256_of(path: Path, chunk: int = 1 << 20) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        while True:
            block = f.read(chunk)
            if not block:
                break
            h.update(block)
    return h.hexdigest()


def render_manifest(rows: list[dict]) -> str:
    lines = [
        "# cache/MANIFEST.md — model artifacts",
        "",
        "Generated by tools/download_models.py. Every row is a file on disk with its sha256;",
        "re-run `--manifest` after copying models from the USB stick to re-verify.",
        "",
        "| name | repo | revision | file | sha256 | size (MB) | license |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in sorted(rows, key=lambda r: r["name"]):
        lines.append(
            f"| {r['name']} | {r['repo']} | {r['revision'][:12]} | {r['file']} | "
            f"`{r['sha256']}` | {r['size_bytes'] / 1e6:,.1f} | {r['license']} |"
        )
    lines += [
        "",
        "## Converting a model that has no official GGUF",
        "",
        "```",
        "git clone https://github.com/ggml-org/llama.cpp && cd llama.cpp",
        "pip install -r requirements.txt",
        "huggingface-cli download <org>/<model> --local-dir /tmp/hf-model",
        "python convert_hf_to_gguf.py /tmp/hf-model --outtype f16 --outfile /tmp/model-f16.gguf",
        "cmake -B build && cmake --build build -j",
        "./build/bin/llama-quantize /tmp/model-f16.gguf cache/models/<name>/<name>.gguf Q4_K_M",
        "uv run python tools/download_models.py --manifest   # picks the file up and hashes it",
        "```",
        "",
    ]
    return "\n".join(lines)


def write_manifest(rows: list[dict]) -> None:
    MANIFEST.write_text(render_manifest(rows), encoding="utf-8")
    LEDGER.write_text(yaml.safe_dump({"artifacts": rows}, sort_keys=False), encoding="utf-8")


def read_ledger() -> list[dict]:
    if not LEDGER.exists():
        return []
    return yaml.safe_load(LEDGER.read_text(encoding="utf-8")).get("artifacts", [])


def hf_api():
    try:
        from huggingface_hub import HfApi
    except ImportError:
        sys.exit("huggingface_hub missing — run `uv sync --extra hf`")
    return HfApi()


def verify(entries: list[Entry]) -> int:
    api = hf_api()
    bad = 0
    for e in entries:
        try:
            info = api.model_info(e.repo, revision=e.revision, files_metadata=False)
            files = [s.rfilename for s in info.siblings or []]
            matches = fnmatch.filter(files, e.file)
            status = "OK " if matches else "NO-MATCH"
            print(f"[{status}] {e.name:<26} {e.repo} @ {info.sha[:12]}")
            for m in matches[:5]:
                print(f"          match: {m}")
            if not matches:
                bad += 1
                ggufs = [f for f in files if f.endswith((".gguf", ".bin"))][:12]
                print("          available: " + (", ".join(ggufs) or "(no gguf/bin files)"))
        except Exception as exc:  # noqa: BLE001 — report every failure, keep going
            bad += 1
            print(f"[MISSING] {e.name:<26} {e.repo}: {type(exc).__name__}: {exc}")
    print(
        f"\n{len(entries) - bad}/{len(entries)} entries resolve. Fix cache/models.yaml and flip "
        "`verified: true` for the ones that do."
    )
    return 1 if bad else 0


def download(entry: Entry) -> dict:
    from huggingface_hub import hf_hub_download

    api = hf_api()
    info = api.model_info(entry.repo, revision=entry.revision)
    files = [s.rfilename for s in info.siblings or []]
    matches = fnmatch.filter(files, entry.file)
    if not matches:
        raise FileNotFoundError(f"{entry.repo}: no file matches {entry.file!r}")
    if len(matches) > 1:
        print(f"  {entry.name}: {len(matches)} matches, taking the first: {matches[0]}")
    fname = matches[0]
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    local = hf_hub_download(entry.repo, fname, revision=info.sha, local_dir=CACHE_DIR / entry.name)
    path = Path(local)
    return {
        "name": entry.name,
        "repo": entry.repo,
        "revision": info.sha,
        "file": str(path.relative_to(REPO_ROOT)),
        "sha256": sha256_of(path),
        "size_bytes": path.stat().st_size,
        "license": entry.license,
    }


def rebuild_from_disk(entries: list[Entry]) -> list[dict]:
    """Hash whatever is in cache/models/<name>/ (e.g. copied from USB) and keep known metadata."""
    known = {r["file"]: r for r in read_ledger()}
    by_name = {e.name: e for e in entries}
    rows = []
    for path in sorted(CACHE_DIR.rglob("*")):
        if not path.is_file() or path.suffix not in (".gguf", ".bin"):
            continue
        rel = str(path.relative_to(REPO_ROOT))
        name = path.relative_to(CACHE_DIR).parts[0]
        e = by_name.get(name)
        prev = known.get(rel, {})
        rows.append(
            {
                "name": name,
                "repo": prev.get("repo", e.repo if e else "?"),
                "revision": prev.get("revision", "local"),
                "file": rel,
                "sha256": sha256_of(path),
                "size_bytes": path.stat().st_size,
                "license": prev.get("license", e.license if e else "?"),
            }
        )
    return rows


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--verify", action="store_true", help="check every repo/file on HF (network)")
    ap.add_argument("--name", action="append", default=[], help="download this entry (repeatable)")
    ap.add_argument("--all", action="store_true", help="download every verified entry")
    ap.add_argument("--force-unverified", action="store_true", help="also download verified: false")
    ap.add_argument(
        "--manifest", action="store_true", help="rebuild MANIFEST.md from files on disk"
    )
    ap.add_argument("--list", action="store_true", help="print the shortlist and exit")
    args = ap.parse_args(argv)

    entries = load_entries()
    if args.list or not any((args.verify, args.name, args.all, args.manifest)):
        for e in entries:
            flag = "verified" if e.verified else "UNVERIFIED"
            print(f"{e.name:<26} tier {e.tier:<4} {e.repo:<45} {e.file:<24} {flag}")
        return 0
    if args.verify:
        return verify(entries)
    if args.manifest:
        rows = rebuild_from_disk(entries)
        write_manifest(rows)
        print(f"manifest: {len(rows)} artifacts → {MANIFEST}")
        return 0

    wanted = [e for e in entries if e.name in args.name] if args.name else []
    if args.all:
        wanted = [e for e in entries if e.verified or args.force_unverified]
    missing = set(args.name) - {e.name for e in wanted}
    if missing:
        sys.exit(f"unknown --name: {', '.join(sorted(missing))}")
    if not wanted:
        sys.exit("nothing to download: no verified entries (run --verify, edit models.yaml)")

    rows = {r["file"]: r for r in read_ledger()}
    for e in wanted:
        if not e.verified and not args.force_unverified:
            print(f"skip {e.name}: unverified")
            continue
        print(f"downloading {e.name} from {e.repo} ...")
        row = download(e)
        rows[row["file"]] = row
        print(f"  {row['file']}  sha256={row['sha256'][:16]}…  {row['size_bytes'] / 1e6:,.1f} MB")
        write_manifest(list(rows.values()))  # after every file: partial progress survives
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
