#!/usr/bin/env python3
"""Generate schemas/extraction.gbnf from schemas/extraction.schema.json.

Uses the vendored llama.cpp converter (tools/vendor/llama_cpp/json_schema_to_grammar.py,
MIT) so the grammar is exactly what llama.cpp would build from the same schema at runtime.
Offline; no model needed. Run ``make gbnf`` after every schema change and commit both files.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:  # allow `python tools/gen_gbnf.py` without installing
    sys.path.insert(0, str(REPO_ROOT))

from tools.vendor.llama_cpp.json_schema_to_grammar import SchemaConverter  # noqa: E402

DEFAULT_SCHEMA = REPO_ROOT / "schemas" / "extraction.schema.json"
DEFAULT_OUT = REPO_ROOT / "schemas" / "extraction.gbnf"

# Property order in the generated grammar == order the model must emit keys. Putting the
# cheap, classifying fields first lets small models commit to the event type before the
# free-text fields (same trick as PRD "tier-0 rules first").
PROP_ORDER = [
    "event_type",
    "warning_id",
    "agency",
    "issued_at",
    "valid_from",
    "valid_to",
    "location_name",
    "geometry",
    "entities",
]


def schema_to_gbnf(schema: dict, url: str = "file://schema.json") -> str:
    converter = SchemaConverter(
        prop_order={name: i for i, name in enumerate(PROP_ORDER)},
        allow_fetch=False,
        dotall=False,
        raw_pattern=False,
    )
    resolved = converter.resolve_refs(schema, url)
    converter.visit(resolved, "")
    return converter.format_grammar()


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--schema", type=Path, default=DEFAULT_SCHEMA)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--check", action="store_true", help="exit 1 if the file on disk is stale")
    args = ap.parse_args(argv)

    schema = json.loads(args.schema.read_text(encoding="utf-8"))
    grammar = schema_to_gbnf(schema, url=f"file://{args.schema}")
    rel = args.schema.relative_to(REPO_ROOT)
    header = f"# generated by tools/gen_gbnf.py from {rel} — do not edit\n"
    text = header + grammar
    if not text.endswith("\n"):
        text += "\n"

    if args.check:
        current = args.out.read_text(encoding="utf-8") if args.out.exists() else ""
        if current != text:
            print(f"{args.out} is stale — run `make gbnf`")
            return 1
        print(f"{args.out} up to date")
        return 0

    args.out.write_text(text, encoding="utf-8")
    print(f"wrote {args.out} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
